### ISSUE TITLE
request another implementation of get_imaging in Julia

### ISSUE THREAD

**Issue by mcfefa** [neheller/kits21#20]
Is it possible to get another implementation of get_imaging in Julia?

**Comment by neheller** [comment]
Sure! I'll read up on Julia and give it a go.

**Comment by neheller** [comment]
Okay I gave it a try. How does this look? Apologies if this is terrible coding practice for Julia.

https://github.com/neheller/kits21/blob/official-dataset-freeze/kits21/starter_code/get_imaging.jl

**Comment by neheller** [comment]
This branch has been merged to master so the file is here now

https://github.com/neheller/kits21/blob/master/kits21/starter_code/get_imaging.jl

**Comment by neheller** [comment]
I'm closing this for now. Feel free to reopen if the script isn't working for you.
