### ISSUE TITLE
Aggregated data

### ISSUE THREAD

**Issue by SpyridoulaZagkou4** [neheller/kits21#29]
Could you provide aggregated segmentation, with ureter,artery,vein etc.. ,besides kidney and tumor?

**Comment by neheller** [comment]
A few weeks ago we announced that we would be reducing the scope of the challenge to exclude ureter, artery, and vein. My apologies for this change, we simply did not have the bandwidth to ensure high-quality labels for so many complex regions this year. You can read more about this decision on Discourse here: https://discourse.kits-challenge.org/t/kits21-challenge-update/354
