### ISSUE TITLE
Can't get imaging.nii.gz after run get_imaging.py

### ISSUE THREAD

**Issue by charrywhite** [neheller/kits21#39]
Hello,

I meet a problem after I run get_imaging.py. In my downloaded data folder,  it seems imaging.nii.gz is missing. I would like to ask how can I access the imaging.nii.gz files?  Hope for your reply :)

**Comment by neheller** [comment]
The `get_imaging.py` script should download the files and place them at `kits21/data/case_XXXXX/imaging.nii.gz` for each of the 300 cases. Are they not showing up there? Is the script printing any messages to the console when it runs?

**Comment by charrywhite** [comment]
Thanks for your reply.  It doesn't really run get_imaging.py when I used python3 kits21/starter_code/get_imaging.py previously. Now I change python3 to python and it works!
