### ISSUE TITLE
get_imaging.py experience issue

### ISSUE THREAD

**Issue by dannyhow12** [neheller/kits21#48]
I seem to be unable to run the get_imaging.py script to load the images. 
![Image](https://user-images.githubusercontent.com/90441440/140692878-7f19db76-5d79-4020-aef8-db7ac2e6f1ea.jpeg)

**Comment by neheller** [comment]
Interesting. It just freezes there? How long did you let it run? It may take quite a long time on slow internet connections. If you look at your resource monitor, does it show data being downloaded?

**Comment by dannyhow12** [comment]
Yeah, it seem to freeze there. I left it like that for around 30 minutes, but it still came up to the same issue where it does not have anything extra. 
I then attempted to download the dataset from the Kits19 dataset, however the dimensions do not match
As for your last question, no it does not show any data being downloaded at my monitor.

**Comment by neheller** [comment]
I created a new file called `get_imaging_v2.py` which might solve this issue. Please give it a try and let me know how it goes.

**Comment by neheller** [comment]
- Sorry, didn't mean to close
