### ISSUE TITLE
Strange image.nii.gz 

### ISSUE THREAD

**Issue by ZhangxinruBIT** [neheller/kits21#51]
Hello,
I have successfully run the get_Imaging.py file and got the image.nii.gz under the corresponding case folder. But the each image.nii.gz looks strange. Their grayscale values are almost all zero, with some very small negative numbers. That means when I opend the image.nii.gz by ITK-SNAP, I can not see the any useful image information.

**Comment by Ixixuw** [comment]
> 



> Hello, I have successfully run the get_Imaging.py file and got the image.nii.gz under the corresponding case folder. But the each image.nii.gz looks strange. Their grayscale values are almost all zero, with some very small negative numbers. That means when I opend the image.nii.gz by ITK-SNAP, I can not see the any useful image information.

Hello,
I ran get_Imaging_v2.py solved the problem.
