### ISSUE TITLE
Dataset Description

### ISSUE THREAD

**Issue by ansariyusuf** [neheller/kits21#53]
Kindly add the dataset description to the repo (e.g., number of cases, demographics, etc.)

**Comment by neheller** [comment]
The [publication](https://www.sciencedirect.com/science/article/abs/pii/S1361841520301857) referenced at the bottom of the readme has a description like this. If you'd like detailed information about each case, I'd recommend looking at the [kits.json](https://github.com/neheller/kits21/blob/master/kits21/data/kits.json) file.
