### ISSUE TITLE
KiTS21 papers no longer available on openreview

### ISSUE THREAD

**Issue by ancestor-mithril** [neheller/kits21#62]
Hi!
When accessing the links from the KiTS21 website to see the papers from openreview, the following message appears:
![image](https://user-images.githubusercontent.com/58839912/236837012-8fbca425-24f8-4a6c-99fd-57ea00a0523a.png)

**Comment by neheller** [comment]
Thanks for bringing this to our attention! No idea what's going on. I will look into it.

**Comment by neheller** [comment]
Sorry for the delay. I have redirected these links to their published locations.
